settingUpDb2
bookofrecipes/main_project pull request #19
Opened 2020-12-19 19:05 UTC by mvrlrd

2020-12-19 20:14 UTC, gulya-a-a-a requested changes
Надо подумать еще над структурой базы. Я тоже посмотрю, потому что пока я не очень понимаю, как сохраняются в базу эти вот Relation объекты)

2020-12-19 20:14 UTC, gulya-a-a-a commented on app/build.gradle
> +}
allprojects блок можно удалить, он есть в build.gradle всего проекта)

2020-12-19 20:14 UTC, gulya-a-a-a commented on app/src/main/java/ru/geekbrains/bookofrecipes/data/local/entity/cross_ref/RecipeNutrientCrossRef.kt
> +    val title: String
Вот это не очень хорошо, потому что обычно поля идентифицируются по ID, потому что сравнение строк - более тяжелая операция, хоть названия в нашем случае и будут, скорее всего, уникальными.

2020-12-19 20:14 UTC, gulya-a-a-a commented on app/src/main/java/ru/geekbrains/bookofrecipes/data/local/entity/cross_ref/RecipeStepCrossRef.kt
> +    val number: Int
А вот это вообще решение не очень, потому что номера шагов у всех рецептов одинаковые. Надо еще подумать, как их сохранять.

2020-12-19 20:14 UTC, gulya-a-a-a commented on app/src/main/java/ru/geekbrains/bookofrecipes/data/local/entity/relations/RecipeWithSteps.kt
> +    val steps : List<Step>
А можно было бы объединить их втроем: Recipe, Ingredients и Steps? Чтобы два раза в базу не ходить?)

2020-12-19 20:14 UTC, gulya-a-a-a commented on app/src/main/java/ru/geekbrains/bookofrecipes/data/response/RecipeInformationResponse.kt
> +    @SerializedName("analyzedInstructions") val instruction: List<Instruction>?,
Тут я бы тоже придрался, что у тебя перемешаны и классы, в которые парсится JSON, и Entity. Я понимаю, что данные одни и те же, но начинаешь путаться, что к чему относится.

2020-12-19 20:14 UTC, gulya-a-a-a commented on app/src/main/java/ru/geekbrains/bookofrecipes/data/local/entity/Instruction.kt
> +    val number: Int,
Вот тут будет коллизия, потому что во всех рецептах номера шагов 1,2,3. Так что у тебя будут храниться только шаги от последнего рецепта. Мне кажется, лучше добавить какой-нибудь `@PrimaryKey(autoGenerate = true)`, чтобы они отличались.

2020-12-20 10:13 UTC, mvrlrd commented on app/src/main/java/ru/geekbrains/bookofrecipes/data/local/entity/Instruction.kt
> +    val number: Int,
согласен, заменил на id autogenerated

2020-12-20 10:14 UTC, mvrlrd commented on app/src/main/java/ru/geekbrains/bookofrecipes/data/local/entity/relations/RecipeWithSteps.kt
> +    val steps : List<Step>
мне кажется нет. потому что ингредиенты одни и те же входят в разные блюда, но шаги везде разные

2020-12-21 15:23 UTC, merged